apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: appmesh-demo
  region: us-east-1
vpc:
  subnets:
    private:
      us-east-1b: { id: subnet-0284be16fb5d078c5 }
      us-east-1a: { id: subnet-0a901b3eaf14d5bc8 }

