apiVersion: appmesh.k8s.aws/v1beta1
kind: VirtualNode
metadata:
  name: color-green
  namespace: staging
spec:
  meshName: cloudzone-staging
  listeners:
  - portMapping:
      port: 8080
      protocol: http
  serviceDiscovery:
    cloudMap:
      serviceName: color
      namespaceName: appmesh.demo.local
